import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       <div className="max-w-7xl mx-auto">
         <Navbar />     {/* ← Your Navbar */}
        {children}
       </div>
      </body>
    </html>
  );
}
